# Actividad de Investigación #4: Explorando Pandas y Web ScrapingTarea
### Autor: Anthony Navarro Aguilar

Comprender cómo Pandas puede integrarse con otras bibliotecas como lxml y BeautifulSoup4 para procesar datos de la web.

`NOTA: recordar contar con las dependencias pip install lxml BeautifulSoup4`

In [1]:
import pandas as pd

#Se realiza el proceso de web scrapping
df_web = pd.read_html('https://gee.bccr.fi.cr/IndicadoresEconomicos/Cuadros/frmConsultaTCVentanilla.aspx',encoding='utf-8', decimal=',', thousands='.')

In [2]:
df_web[2]

,0,1,2,3,4,5
0,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,503.00,517.00,14.00,20/11/2024 01:23 p.m.
2,NaN,Banco Nacional de Costa Rica,503.00,517.00,14.00,20/11/2024 04:27 p.m.
3,NaN,Banco Popular y de Desarrollo Comunal,501.00,515.00,14.00,18/11/2024 01:29 p.m.
4,Bancos privados,Banco BAC San José S.A.,503.00,517.00,14.00,20/11/2024 12:57 p.m.
5,NaN,Banco BCT S.A.,500.00,518.00,18.00,20/11/2024 05:37 p.m.
6,NaN,Banco Cathay de Costa Rica S.A.,502.00,520.00,18.00,20/11/2024 12:41 p.m.
7,NaN,Banco CMB,498.00,522.00,24.00,19/11/2024 09:43 a.m.
8,NaN,Banco Davivienda (Costa Rica) S.A,500.00,518.00,18.00,20/11/2024 01:10 p.m.
9,NaN,Banco General (Costa Rica) S.A.,501.00,516.00,15.00,20/11/2024 01:01 p.m.
10,NaN,Banco Improsa S.A.,499.00,517.00,18.00,20/11/2024 01:18 p.m.
11,NaN,Banco Lafise S.A.,498.00,516.00,18.00,20/11/2024 09:26 a.m.
12,NaN,Banco Promérica S.A.,499.00,517.00,18.00,20/11/2024 05:03 p.m.
13,NaN,Banco Scotiabank de Costa Rica S.A.,498.00,516.00,18.00,20/11/2024 01:32 p.m.
14,NaN,Prival Bank (Costa Rica) S.A,497.00,514.00,17.00,19/11/2024 09:13 a.m.
15,Financieras,Financiera Cafsa S.A.,501.00,517.00,16.00,20/11/2024 06:08 p.m.
16,NaN,Financiera Comeca S.A.,497.00,519.00,22.00,20/11/2024 11:52 a.m.
17,NaN,Financiera MultiMoney S.A.,505.00,516.00,11.00,20/11/2024 01:23 p.m.
18,Mutuales de Vivienda,Grupo Mutual Alajuela - La Vivienda de Ahorro ...,503.00,515.00,12.00,12/11/2024 04:48 p.m.
19,NaN,Mutual Cartago de Ahorro y Préstamo,503.00,515.00,12.00,13/11/2024 01:20 p.m.
20,Cooperativas,Coope-ANDE N°1 R.L.,503.00,517.50,14.50,20/11/2024 03:34 p.m.
21,NaN,Coopecaja R.L.,503.00,517.00,14.00,20/11/2024 05:44 p.m.
22,NaN,Coopemep R.L.,501.00,515.00,14.00,20/11/2024 02:16 p.m.
23,NaN,Cooperativa COOCIQUE R.L.,506.00,521.00,15.00,20/11/2024 04:54 p.m.
24,NaN,Cooperativa Coopealianza R.L.,501.00,517.00,16.00,20/11/2024 04:52 p.m.
25,NaN,Cooperativa CREDECOOP R.L.,500.00,518.00,18.00,14/11/2024 04:30 p.m.
26,NaN,Cooperativa Nacional de Educadores R.L. (COOPE...,503.00,516.00,13.00,20/11/2024 03:35 p.m.
27,NaN,Cooperativa San Marcos R.L.,501.00,514.00,13.00,19/11/2024 09:56 a.m.
28,Casas de Cambio,Airpak Casa de Cambio,505.00,525.00,20.00,20/11/2024 05:40 p.m.
29,NaN,ARI Casa de Cambio Internacional S.A.,506.10,512.33,6.23,20/11/2024 01:03 p.m.
30,NaN,Casa de Cambio Global Exchange,425.37,593.39,168.02,20/11/2024 09:09 p.m.
31,NaN,Casa de Cambio Teledolar S. A.,503.00,525.00,22.00,20/11/2024 05:23 p.m.
32,Puestos de Bolsa,"BCT Valores, Puesto De Bolsa, S.A.",500.00,518.00,18.00,20/11/2024 05:46 p.m.
33,NaN,"BN Valores S.A., Puesto de Bolsa",501.00,515.00,14.00,20/11/2024 11:52 a.m.
34,NaN,Mercado Valores de Costa Rica Puesto de Bolsa,499.00,517.00,18.00,20/11/2024 12:18 p.m.
35,NaN,PB Inversiones SAMA,500.00,516.00,16.00,20/11/2024 12:03 p.m.
36,NaN,"Popular Valores, Puesto de Bolsa",501.00,515.00,14.00,19/11/2024 09:38 a.m.
37,NaN,NaN,NaN,NaN,NaN,NaN

## Trabajamos en limpiar los datos de la tabla importada

In [3]:
#Importe 38 registro y 6 columnas, debe eliminar dos registros mal importados
print(df_web[2].shape)

#Guardo el dataframe en una variable nueva en memoria
df = df_web[2].copy()
del(df_web) #Elimino el df importado

(38, 6)

In [4]:
#Imprime encabezado de df
df.head(3)

,0,1,2,3,4,5
0,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,503.00,517.00,14.00,20/11/2024 01:23 p.m.
2,NaN,Banco Nacional de Costa Rica,503.00,517.00,14.00,20/11/2024 04:27 p.m.

In [5]:
#Imprime los titulos de la columnas
df.columns

Index([0, 1, 2, 3, 4, 5], dtype='int64')

### Paso1: Lipiar nombres de columnas

- Extraer la fila 0
- Asigno fila 0 como columna

In [6]:
#Extraer fila 0
primera_fila = df.iloc[0]

#Asignar las etiquetas a las columnas
df.columns = primera_fila

#Borrar Fila 0
df.drop(0, inplace=True)

df.head()

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,503.00,517.00,14.00,20/11/2024 01:23 p.m.
2,NaN,Banco Nacional de Costa Rica,503.00,517.00,14.00,20/11/2024 04:27 p.m.
3,NaN,Banco Popular y de Desarrollo Comunal,501.00,515.00,14.00,18/11/2024 01:29 p.m.
4,Bancos privados,Banco BAC San José S.A.,503.00,517.00,14.00,20/11/2024 12:57 p.m.
5,NaN,Banco BCT S.A.,500.00,518.00,18.00,20/11/2024 05:37 p.m.

In [7]:
#Renombrar las columnas
df.rename(columns={'Tipo de Entidad':'Tipo','Entidad Autorizada':'Entidad','Diferencial Cambiario':'Diferencial'}, inplace=True)

df.columns

Index(['Tipo', 'Entidad', 'Compra', 'Venta', 'Diferencial',
       'Última Actualización'],
      dtype='object', name=0)

In [8]:
#Eliminar series con algún valor nulo
df.dropna()

,Tipo,Entidad,Compra,Venta,Diferencial,Última Actualización
1,Bancos públicos,Banco de Costa Rica,503.00,517.00,14.00,20/11/2024 01:23 p.m.
4,Bancos privados,Banco BAC San José S.A.,503.00,517.00,14.00,20/11/2024 12:57 p.m.
15,Financieras,Financiera Cafsa S.A.,501.00,517.00,16.00,20/11/2024 06:08 p.m.
18,Mutuales de Vivienda,Grupo Mutual Alajuela - La Vivienda de Ahorro ...,503.00,515.00,12.00,12/11/2024 04:48 p.m.
20,Cooperativas,Coope-ANDE N°1 R.L.,503.00,517.50,14.50,20/11/2024 03:34 p.m.
28,Casas de Cambio,Airpak Casa de Cambio,505.00,525.00,20.00,20/11/2024 05:40 p.m.
32,Puestos de Bolsa,"BCT Valores, Puesto De Bolsa, S.A.",500.00,518.00,18.00,20/11/2024 05:46 p.m.

In [9]:
#Completa valores nulos con un valor en especifico
df['Tipo'].fillna('NO valor').tail()

33    NO valor
34    NO valor
35    NO valor
36    NO valor
37    NO valor
Name: Tipo, dtype: object

In [10]:
# Remplazar valores NaN con el último valor no nulo en la misma columna
df['Tipo'].ffill(inplace=True)

C:\Users\antho\AppData\Local\Temp\ipykernel_14600\722260687.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Tipo'].ffill(inplace=True)

In [11]:
df

,Tipo,Entidad,Compra,Venta,Diferencial,Última Actualización
1,Bancos públicos,Banco de Costa Rica,503.00,517.00,14.00,20/11/2024 01:23 p.m.
2,Bancos públicos,Banco Nacional de Costa Rica,503.00,517.00,14.00,20/11/2024 04:27 p.m.
3,Bancos públicos,Banco Popular y de Desarrollo Comunal,501.00,515.00,14.00,18/11/2024 01:29 p.m.
4,Bancos privados,Banco BAC San José S.A.,503.00,517.00,14.00,20/11/2024 12:57 p.m.
5,Bancos privados,Banco BCT S.A.,500.00,518.00,18.00,20/11/2024 05:37 p.m.
6,Bancos privados,Banco Cathay de Costa Rica S.A.,502.00,520.00,18.00,20/11/2024 12:41 p.m.
7,Bancos privados,Banco CMB,498.00,522.00,24.00,19/11/2024 09:43 a.m.
8,Bancos privados,Banco Davivienda (Costa Rica) S.A,500.00,518.00,18.00,20/11/2024 01:10 p.m.
9,Bancos privados,Banco General (Costa Rica) S.A.,501.00,516.00,15.00,20/11/2024 01:01 p.m.
10,Bancos privados,Banco Improsa S.A.,499.00,517.00,18.00,20/11/2024 01:18 p.m.
11,Bancos privados,Banco Lafise S.A.,498.00,516.00,18.00,20/11/2024 09:26 a.m.
12,Bancos privados,Banco Promérica S.A.,499.00,517.00,18.00,20/11/2024 05:03 p.m.
13,Bancos privados,Banco Scotiabank de Costa Rica S.A.,498.00,516.00,18.00,20/11/2024 01:32 p.m.
14,Bancos privados,Prival Bank (Costa Rica) S.A,497.00,514.00,17.00,19/11/2024 09:13 a.m.
15,Financieras,Financiera Cafsa S.A.,501.00,517.00,16.00,20/11/2024 06:08 p.m.
16,Financieras,Financiera Comeca S.A.,497.00,519.00,22.00,20/11/2024 11:52 a.m.
17,Financieras,Financiera MultiMoney S.A.,505.00,516.00,11.00,20/11/2024 01:23 p.m.
18,Mutuales de Vivienda,Grupo Mutual Alajuela - La Vivienda de Ahorro ...,503.00,515.00,12.00,12/11/2024 04:48 p.m.
19,Mutuales de Vivienda,Mutual Cartago de Ahorro y Préstamo,503.00,515.00,12.00,13/11/2024 01:20 p.m.
20,Cooperativas,Coope-ANDE N°1 R.L.,503.00,517.50,14.50,20/11/2024 03:34 p.m.
21,Cooperativas,Coopecaja R.L.,503.00,517.00,14.00,20/11/2024 05:44 p.m.
22,Cooperativas,Coopemep R.L.,501.00,515.00,14.00,20/11/2024 02:16 p.m.
23,Cooperativas,Cooperativa COOCIQUE R.L.,506.00,521.00,15.00,20/11/2024 04:54 p.m.
24,Cooperativas,Cooperativa Coopealianza R.L.,501.00,517.00,16.00,20/11/2024 04:52 p.m.
25,Cooperativas,Cooperativa CREDECOOP R.L.,500.00,518.00,18.00,14/11/2024 04:30 p.m.
26,Cooperativas,Cooperativa Nacional de Educadores R.L. (COOPE...,503.00,516.00,13.00,20/11/2024 03:35 p.m.
27,Cooperativas,Cooperativa San Marcos R.L.,501.00,514.00,13.00,19/11/2024 09:56 a.m.
28,Casas de Cambio,Airpak Casa de Cambio,505.00,525.00,20.00,20/11/2024 05:40 p.m.
29,Casas de Cambio,ARI Casa de Cambio Internacional S.A.,506.10,512.33,6.23,20/11/2024 01:03 p.m.
30,Casas de Cambio,Casa de Cambio Global Exchange,425.37,593.39,168.02,20/11/2024 09:09 p.m.
31,Casas de Cambio,Casa de Cambio Teledolar S. A.,503.00,525.00,22.00,20/11/2024 05:23 p.m.
32,Puestos de Bolsa,"BCT Valores, Puesto De Bolsa, S.A.",500.00,518.00,18.00,20/11/2024 05:46 p.m.
33,Puestos de Bolsa,"BN Valores S.A., Puesto de Bolsa",501.00,515.00,14.00,20/11/2024 11:52 a.m.
34,Puestos de Bolsa,Mercado Valores de Costa Rica Puesto de Bolsa,499.00,517.00,18.00,20/11/2024 12:18 p.m.
35,Puestos de Bolsa,PB Inversiones SAMA,500.00,516.00,16.00,20/11/2024 12:03 p.m.
36,Puestos de Bolsa,"Popular Valores, Puesto de Bolsa",501.00,515.00,14.00,19/11/2024 09:38 a.m.
37,Puestos de Bolsa,NaN,NaN,NaN,NaN,NaN

In [12]:
#Opción1 eliminar con index
df.drop(df.tail(1).index, inplace= True)

#Opción2: eliminar con dropna
df.dropna(inplace=True)

# Realizar análisis sobre los datos limpios

In [13]:
# Consultar la entidad con la venta mas baja
tipo_venta_min = df['Venta'].min()


entidades_con_min = df[df['Venta'] == tipo_venta_min]['Entidad']

print('Tipo cambio minimo: ', tipo_venta_min)
print('Entidad/s', entidades_con_min)

Tipo cambio minimo:  512.33
Entidad/s 29    ARI Casa de Cambio Internacional S.A.
Name: Entidad, dtype: object

In [14]:
#Conultar la entidad con venta mal alta
tipo_venta_max = df['Venta'].max()

entidades_con_max = df[df['Venta'] == tipo_venta_max]

entidades_con_max

,Tipo,Entidad,Compra,Venta,Diferencial,Última Actualización
30,Casas de Cambio,Casa de Cambio Global Exchange,425.37,593.39,168.02,20/11/2024 09:09 p.m.

In [15]:
entidades_con_max = df[df['Venta'] == tipo_venta_max]['Entidad']
entidades_con_max

30    Casa de Cambio Global Exchange
Name: Entidad, dtype: object

In [16]:
#df.loc[:5,['Entidad','Compra','Venta']]
#df.loc[:,['Entidad','Compra','Venta']]
df.loc[[1,20,13,14],['Entidad','Compra','Venta']]

0                               Entidad  Compra   Venta
1                   Banco de Costa Rica  503.00  517.00
20                  Coope-ANDE N°1 R.L.  503.00  517.50
13  Banco Scotiabank de Costa Rica S.A.  498.00  516.00
14         Prival Bank (Costa Rica) S.A  497.00  514.00

In [17]:
print(df.dtypes)

0
Tipo                    object
Entidad                 object
Compra                  object
Venta                   object
Diferencial             object
Última Actualización    object
dtype: object

In [18]:
#Promedio de compra
promedio_compra = df['Compra'].astype(float).mean()
promedio_compra

np.float64(499.1519444444445)

In [19]:
#Tipado de columnas
columnas_float = ['Compra','Venta','Diferencial']
df[columnas_float] = df[columnas_float].apply(pd.to_numeric)
print(df.dtypes)

0
Tipo                     object
Entidad                  object
Compra                  float64
Venta                   float64
Diferencial             float64
Última Actualización     object
dtype: object

In [20]:
#Promedio de venta
promedio_venta = df['Venta'].mean()
promedio_venta

np.float64(519.2838888888889)

In [21]:
df.describe()

0          Compra       Venta  Diferencial
count   36.000000   36.000000    36.000000
mean   499.151944  519.283889    20.131944
std     12.865186   12.987587    25.576304
min    425.370000  512.330000     6.230000
25%    499.750000  515.750000    14.000000
50%    501.000000  517.000000    16.000000
75%    503.000000  518.000000    18.000000
max    506.100000  593.390000   168.020000

In [22]:
df.groupby('Tipo')['Venta'].describe()

,count,mean,std,min,25%,50%,75%,max
Tipo,,,,,,,,
Bancos privados,11.0,517.363636,2.157440,514.00,516.0000,517.0,518.0000,522.00
Bancos públicos,3.0,516.333333,1.154701,515.00,516.0000,517.0,517.0000,517.00
Casas de Cambio,4.0,538.930000,36.794662,512.33,521.8325,525.0,542.0975,593.39
Cooperativas,8.0,516.937500,2.111829,514.00,515.7500,517.0,517.6250,521.00
Financieras,3.0,517.333333,1.527525,516.00,516.5000,517.0,518.0000,519.00
Mutuales de Vivienda,2.0,515.000000,0.000000,515.00,515.0000,515.0,515.0000,515.00
Puestos de Bolsa,5.0,516.200000,1.303840,515.00,515.0000,516.0,517.0000,518.00